#pragma once

#include <cassert>
#include <vector>
#include <string>
#include <cstdint>
#include <functional>
#include <memory>
#include <ctime>
#include <cmath>

#include <QObject>
#include <QWidget>
#include <QMainWindow>
#include <QStackedWidget>
#include <QLabel>
#include <QPushButton>
#include <QLineEdit>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QPainter>
#include <QTimer>
#include <QKeyEvent>
#include <QMessageBox>
#include <QDialog>
#include <QFont>
#include <QColor>
#include <QPointF>
#include <QRandomGenerator>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QFile>
#include <QDir>
#include <QCoreApplication>
#include <QVector>
#include <QString>
#include <QShowEvent>
