#pragma once

enum {
    PROP_ID_TURN = 1,
    PROP_ID_ROUND,
    PROP_ID_POINTS,
    PROP_ID_PHASE,
    PROP_ID_MESSAGE,
    PROP_ID_TRAJECTORY,
    PROP_ID_GAME_OVER,
    PROP_ID_PAUSED,
    PROP_ID_COST_PREVIEW,
    PROP_ID_SAVE_RESULT,
    PROP_ID_SQUARE_HIT,
};
